[workspace]

members = [
    "c8common",
    "c8asm",
    "c8asm-proc",
    "c8int",
    "c8hooks",
    "c8runner",
]

resolver = "2"

[workspace.dependencies]
chip8_base = "0.2.0"
log = "0.4.17"
tap = "1.0.1"
